### ISSUE TITLE
Error when install package

### ISSUE THREAD

**Issue by mbasirati** [keyone2693/ImageResizer.AspNetCore#6]
I create new asp.core 2.1 project and then install package and then that error occured:

> Install-Package : NU1107: Version conflict detected for Microsoft.Extensions.Caching.Abstractions. Install/reference Microsoft.Extensions.Caching.Abstractions 3.1.4 directly 
> to project WebApplication1 to resolve this issue. 
>  WebApplication1 -> ImageResizer.AspNetCore 1.9.0 -> Microsoft.Extensions.Caching.Abstractions (>= 3.1.4) 
>  WebApplication1 -> Microsoft.AspNetCore.App 2.2.0 -> Microsoft.Extensions.Caching.Abstractions (>= 2.2.0 && < 2.3.0).
> At line:1 char:1
> + Install-Package ImageResizer.AspNetCore
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package restore failed. Rolling back package changes for 'WebApplication1'.
> At line:1 char:1
> + Install-Package ImageResizer.AspNetCore
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
What's the problem?

**Comment by keyone2693** [comment]
Hi 
You have this package in your project
**Microsoft.Extensions.Caching.Abstractions**
and the **ImageResizer.AspNetCore**  uses the same package 

the problem is you have the lower version and the **ImageResizer.AspNetCore** has the higher

I think if you remove the **Microsoft.Extensions.Caching.Abstractions** package from your project
and then try insyalling  **ImageResizer.AspNetCore**  it will be good to go
